title: Kevin Ho
logo: /assets/img/headshot_rounded_small.png
description: Data & Financial Analyst with 3+ years of experience using Excel, SQL, Power BI, and Python to automate workflows, improve reporting efficiency, and deliver actionable insights. Adept at streamlining operations, analyzing performance trends, and building dashboards that drive strategic decisions.
show_download: false
theme: jekyll-theme-minimal
