title: Kevin Ho
logo: /assets/img/headshot_rounded_small.png
description: Data & Financial Analyst with 3+ years of experience using Excel, SQL, Power BI, and Python to automate workflows, improve reporting efficiency, and deliver actionable insights.
